version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST}
      - N8N_SMTP_PORT=${SMTP_PORT}
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASS}
      - N8N_SMTP_SENDER=${SMTP_SENDER}
      - N8N_SMTP_REPLY_TO=${SMTP_REPLY_TO}
      - N8N_SMTP_SSL=true
      - N8N_SMTP_TLS=true
      - N8N_SMTP_USE_SSL=true
      - N8N_SMTP_USE_TLS=true
      - N8N_SMTP_IGNORE_TLS=false
      - N8N_SMTP_SECURE=true
      - N8N_SMTP_REQUIRE_TLS=true
      - N8N_SMTP_AUTH=true
      - N8N_SMTP_AUTH_TYPE=login
      - N8N_SMTP_AUTH_USER=${SMTP_USER}
      - N8N_SMTP_AUTH_PASS=${SMTP_PASS}
      - N8N_SMTP_AUTH_METHOD=PLAIN
      - N8N_SMTP_AUTH_TLS=false
      - N8N_SMTP_AUTH_SSL=false
      - N8N_SMTP_AUTH_REJECT_UNAUTHORIZED=true
