[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
